const UI_NAMES = {
    centers: {
        "1": "ثانوية عبد الرحمان الكواكبي",
        "2": "متوسطة دقعة الطاهر بن الزاوي",
        "3": "ثانوية البشير الإبراهيمي",
        "4": "متوسطة أحمد زبانة",
        "5": "ثانوية لحسيني محمد"
    },
    
    levels: {
        "primary": "أساتذة الطور الابتدائي",
        "middle_secondary": "أساتذة الطور المتوسط والثانوي"
    },
    specs: {
        "arabic": "تخصص اللغة العربية",
        "french": "تخصص اللغة الفرنسية",
        "english": "تخصص اللغة الإنجليزية",
        "sport": "تخصص التربية البدنية والرياضة",
        "others": "باقي التخصصات"
    }
};

const dbLinks = {
    // =========================================================
    // 1. ثانوية عبد الرحمان الكواكبي
    // =========================================================
    "1": {
        "primary": {
            "arabic": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        }
    },

    // =========================================================
    // 2. متوسطة دقعة الطاهر بن الزاوي
    // =========================================================
    "2": { 
        "primary": { 
            "english": {  
                didactique:{1:"https://drive.google.com/drive/folders/15IxfJWDEw9C_yfRIIs5ylxU0ZGGZAVNE?usp=sharing",
                            2:"https://drive.google.com/drive/folders/1wfVk0Ht1r7EmNvlZYLfDQTeBCMGNZ3uP?usp=sharing",
                            3:"https://drive.google.com/drive/folders/1afNDsS7pwzY4IogL8j71VZFhSd8jQy3J?usp=sharing"},

                tasyire:{1:"https://drive.google.com/drive/folders/1Cer2vf6CPlIYkqEWTuJQKeL0WKDaJIQA?usp=sharing",
                         2:"https://drive.google.com/drive/folders/1DMXEzhmW5qeDcCIkinHUu3sODS8GMuBw?usp=sharing",
                         3:"https://drive.google.com/drive/folders/1eHZK_AhNE1B3ClVKoAFI86FD3_IjipBq?usp=sharing"},

                takwime:{1:"https://drive.google.com/drive/folders/10Tlnvz31vm8vXbQwITeM9Sxa4fj3T4Tb?usp=sharing",
                         2:"https://drive.google.com/drive/folders/1kcYwa5kQulcZGl80WWSblyi2P91jj89m?usp=sharing",
                         3:"https://drive.google.com/drive/folders/1nYDQyVw1c5qsB5bP8PcIXQX_KzV7QkZo?usp=sharing"},

                nidame:{1:"https://drive.google.com/drive/folders/1Xs-O0OFvtGrCz4wjxU526yPTio9HUrRK?usp=sharing",
                        2:"https://drive.google.com/drive/folders/1zK8MettMqztZ6o-LsTBy-agee71IrGxG?usp=sharing",
                        3:"https://drive.google.com/drive/folders/1xlq9QXHbFHay7_WFSV8NZpieuPXtSdxD?usp=sharing"},

                akhlakiyate:{1:"https://drive.google.com/drive/folders/1559-c406V7wsBsz5fw5OHz9jaE8GDh9q?usp=sharing",
                             2:"https://drive.google.com/drive/folders/11D8Dah6NPwVvZvRqIPhkEL_Wrhi5ftiX?usp=sharing",
                             3:"https://drive.google.com/drive/folders/1ZjcVDA3ObBve2Qe5uueQRJQ71wqN5yb0?usp=sharing"},

                handasa:{1:"https://drive.google.com/drive/folders/1YjZ1C8Sp_DRzJHIG-BFN-dcEwxjDnjqx?usp=sharing",
                         2:"https://drive.google.com/drive/folders/11RiHPfhRX_zlEm9PrtcyP_Leye_O9UJ-?usp=sharing",
                         3:"https://drive.google.com/drive/folders/1VoUtVMVLfTHQUWciWKjkTp-oAL51QnDc?usp=sharing"},

                wasata:{1:"https://drive.google.com/drive/folders/1TTxKQWUxxvohYRWc0N8Uf23NlHWh7nVX?usp=sharing",
                        2:"https://drive.google.com/drive/folders/1jhnW1i8vzhOckIPalWsqoCu-FQ71jjyY?usp=sharing",
                        3:"https://drive.google.com/drive/folders/1wXOiwpl5XnfOXJDxaW7ok5vl0xvTHDmv?usp=sharing"},

                tachri:{1:"https://drive.google.com/drive/folders/1ys2c2v5fkz7GFTzUOTxmbEAWRYvomb2x?usp=sharing",
                        2:"https://drive.google.com/drive/folders/1xmAHc9X9OcuhmSON3IZgrS1PHsKUVoR-?usp=sharing",
                        3:"https://drive.google.com/drive/folders/1i3Kt9n_3yCgzfRmRCZbxtEsjwOr2Affe?usp=sharing"},

                psycho:{1:"https://drive.google.com/drive/folders/1yE5TM0JugX6H3kkwjK-YgmzA_JV42aCn?usp=sharing",
                        2:"https://drive.google.com/drive/folders/1RECS840svN61GkNpebbbJOUr-7LAXbGZ?usp=sharing",
                        3:"https://drive.google.com/drive/folders/1zUxWLKxP7FwXFg0Kuh8k6usOh1OaZVU5?usp=sharing"},

                informatique:{1:"https://drive.google.com/drive/folders/1GePuEu6dyHMFg0jgywhyEzdpqKYivogZ?usp=sharing",
                              2:"https://drive.google.com/drive/folders/10gBH0FmkhboD-OriFMsKj1J-0sncr4KJ?usp=sharing",
                              3:"https://drive.google.com/drive/folders/1DSG0p81Tlv5qKUg2FGLy3MNWa1A8_jxw?usp=sharing"},
                videos: [
                    { title: "الدرس التطبيقي الأول (نظام البطاقات المهنية):", url: "https://drive.google.com/file/d/1lxcSIQbsYCz5XiJPTTv8joTIZFBdcvaf/view?usp=sharing" },
                    { title: "الدرس التطبيقي الثاني (معالج النصوص):", url: "" },
                    { title: "الدرس التطبيقي الثالث (كيفية فتح بريد الكتروني):", url: "" },
                    { title: "الدرس التطبيقي الرابع (مدخل عن كانفا):", url: "" }
                ]
            },
            "sport": { 
                didactique:{1:"https://drive.google.com/drive/folders/1iXSVVF0QFbGmV2P018QWXWCvFPdwBFEO?usp=drive_link",
                            2:"https://drive.google.com/drive/folders/1slSLw9GKc76hM3wZFcOckQbPgM0WzO1o?usp=drive_link",
                            3:"https://drive.google.com/drive/folders/1Estv3846x3eFF8GLPYC0WPlCueclfDsM?usp=drive_link"},

                tasyire:{1:"https://drive.google.com/drive/folders/1m3CF5lbr4O8RB4iD_ZCkhcflXyQCKpXe?usp=drive_link",
                         2:"https://drive.google.com/drive/folders/1edso02zVxpboGh--iKwEBcEawRBhZPa8?usp=drive_link",
                         3:"https://drive.google.com/drive/folders/118bj7hDFXWzcVnsHxZgE67d9Xc4qMHgy?usp=drive_link"},

                takwime:{1:"https://drive.google.com/drive/folders/1aHPB6I2jIN4mAMV3IH4Lttp0yEUNWMWA?usp=drive_link",
                         2:"https://drive.google.com/drive/folders/1rf71lcP5ZKjHL0DGwYyElon6ib95Uqed?usp=drive_link",
                         3:"https://drive.google.com/drive/folders/10tNQV5HBOf8_9gzLscBYmgmrWt9HW_BL?usp=drive_link"},

                nidame:{1:"https://drive.google.com/drive/folders/1urZ_u4XC4K0DJhAnnB8jV73eNH20bxI5?usp=drive_link",
                        2:"https://drive.google.com/drive/folders/1UrEIeJEOBDbHTs5uiSYYLBOlZU8K1B1A?usp=drive_link",
                        3:"https://drive.google.com/drive/folders/1xX0ogqjhaAOugblb4Xi6cTqbgOEhHCih?usp=drive_link"},

                akhlakiyate:{1:"https://drive.google.com/drive/folders/1cbfr0uUInBCn0a7XBIpu3HhnccKYjzpC?usp=drive_link",
                             2:"https://drive.google.com/drive/folders/1X-n-JtDQ6X1iycMQnni6QALcdyqBTSuP?usp=drive_link",
                             3:"https://drive.google.com/drive/folders/1wq0ACqGNBHLP0bYDpUrtSTv7l7-koVLP?usp=drive_link"},

                handasa:{1:"https://drive.google.com/drive/folders/1JNuc5n7JP-HDWdvn0y_yvby-Ua7yp7M1?usp=drive_link",
                         2:"https://drive.google.com/drive/folders/1_6aJ2_prZ0qJQOHH43wFrgGHDFFI68H3?usp=drive_link",
                         3:"https://drive.google.com/drive/folders/11iVmakYM4MgmK2fJp5jVapMac6Du4JLU?usp=drive_link"},

                wasata:{1:"https://drive.google.com/drive/folders/1y2WM1Wr47Qg88zcht3wY5gr7AdL9WZV5?usp=drive_link",
                        2:"https://drive.google.com/drive/folders/1AAe4lGfCLUjsxLl45fxMzrvP0vp91dw_?usp=drive_link",
                        3:"https://drive.google.com/drive/folders/1HYOMKjWE1YTSQgzQZwclXay2Hpw1754R?usp=drive_link"},

                tachri:{1:"https://drive.google.com/drive/folders/1LVVo1qAdL2nL7YddIE2J_PVRvFhXzXS8?usp=drive_link",
                        2:"https://drive.google.com/drive/folders/1IrDHmi3qTyjn5Tl0yWsIWRJ_6aBwjnls?usp=drive_link",
                        3:"https://drive.google.com/drive/folders/1iVOW2wzQ6NqXpQjFWcw499gUdC8mXNh3?usp=drive_link"},

                psycho:{1:"https://drive.google.com/drive/folders/1Wgp4QicLpynsmbx9bgrMsVc8gKbQLtWS?usp=drive_link",
                        2:"https://drive.google.com/drive/folders/10aqkjQWYWEyb5OSSumvMIt4o2nA2pziA?usp=drive_link",
                        3:"https://drive.google.com/drive/folders/1yPOf-RVamUME7nxgwdP1sp2Ht46SYo7P?usp=drive_link"},

                informatique:{1:"https://drive.google.com/drive/folders/1MB8AlkQG4xwIoGFsDWOF_09rXnob8X9l?usp=drive_link",
                              2:"https://drive.google.com/drive/folders/1u804xOXy1Ws7pk6uMJui1HEPpGy6sk7k?usp=drive_link",
                              3:"https://drive.google.com/drive/folders/1yhTq2Ize1fsX8SvwaB_NiBrrGv9jGS3m?usp=drive_link"},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        }
    },

    // =========================================================
    // 3. ثانوية البشير الإبراهيمي
    // =========================================================
    "3": {
        "middle_secondary": {
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "english": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "sport": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "others": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        }
    },

    // =========================================================
    // 4. متوسطة أحمد زبانة 
    // =========================================================
    "4": {
        "primary": {
            "arabic": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "english": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "sport": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        },
        "middle_secondary": {
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "english": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "sport": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "others": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        }
    },

    // =========================================================
    // 5. ثانوية لحسيني محمد 
    // =========================================================
    "5": {
        "primary": {
            "arabic": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "english": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "sport": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        },
        "middle_secondary": {
            "french": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "english": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "sport": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            },
            "others": {
                didactique:{1:"",
                            2:"",
                            3:""},
                tasyire:{1:"",
                         2:"",
                         3:""},
                takwime:{1:"",
                         2:"",
                         3:""},
                nidame:{1:"",
                        2:"",
                        3:""},
                akhlakiyate:{1:"",
                             2:"",
                             3:""},
                handasa:{1:"",
                         2:"",
                         3:""},
                wasata:{1:"",
                        2:"",
                        3:""},
                tachri:{1:"",
                        2:"",
                        3:""},
                psycho:{1:"",
                        2:"",
                        3:""},
                informatique:{1:"",
                              2:"",
                              3:""},
                videos: [
                    { title: "الدرس التطبيقي الأول:", url: "" },
                    { title: "الدرس التطبيقي الثاني:", url: "" }
                ]
            }
        }
    }
};

// ==========================================
// إعدادات فتح وغلق الدورات والمقاييس
// ==========================================

// 1. التحكم العام في الدورات
const GLOBAL_CYCLE_STATUS = { 
    1: true,  
    2: false,
    3: false  
};

// 2. التحكم  كل مقياس داخل كل دورة 
const MODULE_CYCLE_STATUS = {
  didactique:   { 1: true, 2: true, 3: true },
  tasyire:      { 1: true, 2: true, 3: true },
  takwime:      { 1: true, 2: true, 3: true },
  nidame:       { 1: true, 2: true, 3: true },
  akhlakiyate:  { 1: true, 2: true, 3: true },
  handasa:      { 1: true, 2: true, 3: true },
  wasata:       { 1: true, 2: true, 3: true },
  tachri:       { 1: true, 2: true, 3: true },
  psycho:       { 1: true, 2: true, 3: true },
  informatique: { 1: true, 2: true, 3: true }
};